import requests
import xml.etree.ElementTree as ET
from xml.dom import minidom
import argparse

# Dictionary to map Speakers (MB) to Yamaha
dict_speakers = {
    "Front Left": "Front_L",
    "Front Right": "Front_R",
    "Center": "Center",
    "LFE": "Subwoofer_1",
    "Surround Right": "Sur_R",
    "Surround Left": "Sur_L",
    "Surround Back Right": "Sur_Back_R",
    "Surround Back Left": "Sur_Back_L"
}

# Dictionary to restore the frequency values
dict_freq = {
    "15.5 Hz": "15.6 Hz",
    "19.6 Hz": "19.7 Hz",
    "24.7 Hz": "24.8 Hz",
    "31.2 Hz": "31.3 Hz",
    "39.3 Hz": "39.4 Hz",
    "49.59 Hz": "49.6 Hz",
    "62.5 Hz": "62.5 Hz",
    "78.69 Hz": "78.7 Hz",
    "99.19 Hz": "99.2 Hz",
    "125 Hz": "125.0 Hz",
    "157.5 Hz": "157.5 Hz",
    "198.3 Hz": "198.4 Hz",
    "250 Hz": "250.0 Hz",
    "315 Hz": "315.0 Hz",
    "396.8 Hz": "396.9 Hz",
    "500 Hz": "500.0 Hz",
    "630 Hz": "630.0 Hz",
    "793.7 Hz": "793.7 Hz",
    "1000 Hz": "1.00 kHz",
    "1260 Hz": "1.26 kHz",
    "1590 Hz": "1.59 kHz",
    "2000 Hz": "2.00 kHz",
    "2520 Hz": "2.52 kHz",
    "3170 Hz": "3.17 kHz",
    "4000 Hz": "4.00 kHz",
    "5040 Hz": "5.04 kHz",
    "6350 Hz": "6.35 kHz",
    "8000 Hz": "8.00 kHz",
    "10100 Hz": "10.1 kHz",
    "12700 Hz": "12.7 kHz",
    "16000 Hz": "16.0 kHz"
}

# Dictionary to restore the rounded Q values
dict_q = {
    "0.5": "0.500",
    "0.62": "0.630",
    "0.79": "0.794",
    "1": "1.000",
    "1.25": "1.260",
    "1.58": "1.587",
    "2": "2.000",
    "2.51": "2.520",
    "3.17": "3.175",
    "4": "4.000",
    "5.03": "5.040",
    "6.34": "6.350",
    "8": "8.000",
    "10.07": "10.080"
}

def parse_speaker_name(speaker):
    """
    Function to parse the Speaker Name (MB) to Yamaha Web format
    """
    return dict_speakers[speaker]

def parse_frequency_value(freq):
    """
    Function to parse the Frequency value (MB) to Yamaha Web format
    """
    return dict_freq[freq]

def parse_gain_value(gain):
    """
    Function to parse the Gain value (MB) to Yamaha Web format
    """
    value = gain.split()[0].strip()
    return int(float(value)*10)

def parse_q_value(q):
    """
    Function to parse the Q value (MB) to Yamaha Web format
    """
    return dict_q[q]

def create_filter_element(filter_data: dict):
    """
    Function to create XML elements
    """
    filter_element = ET.Element(f"Band_{filter_data['number']}")

    if 'Frequency' in filter_data:
        freq = ET.SubElement(filter_element, "Freq")
        freq.text = str(filter_data['Frequency'])

    if 'Gain' in filter_data:
        gain = ET.SubElement(filter_element, "Gain")
        val = ET.SubElement(gain, "Val")
        val.text = str(filter_data['Gain'])

    if 'Q factor' in filter_data:
        q = ET.SubElement(filter_element, "Q")
        q.text = str(filter_data['Q factor'])

    return filter_element

def parse_text_to_xml(text):
    """
    Function to parse the text file and create XML structure
    """
    lines = text.strip().split('\n')
    manual_data = ET.Element("Manual_Data")
    current_section = None

    for line in lines:
        line = line.strip()
        if line.endswith('='):
            current_section = ET.SubElement(manual_data, parse_speaker_name(prev_line))
        elif line.startswith('Filter'):
            filter_data = {'number': line.split()[1].strip(':')}
        elif line.startswith('-'):
            key, value = line.split(':')
            if key.strip('- ') == 'Frequency':  
                filter_data[key.strip('- ')] = parse_frequency_value(value.strip())
            if key.strip('- ') == 'Q factor':  
                filter_data[key.strip('- ')] = parse_q_value(value.strip())
            if key.strip('- ') == 'Gain':
                filter_data[key.strip('- ')] = parse_gain_value(value.strip())
                current_section.append(create_filter_element(filter_data))
        prev_line = line

    return manual_data

def create_peq_request_xml(text):
    manual_data = parse_text_to_xml(text)

    root = ET.Element("YAMAHA_AV", cmd="PUT")
    system = ET.SubElement(root, "System")
    speaker_preout = ET.SubElement(system, "Speaker_Preout")
    pattern_1 = ET.SubElement(speaker_preout, "Pattern_1")
    peq = ET.SubElement(pattern_1, "PEQ") 
    peq.append(manual_data)

    #return ET.ElementTree(root)
    return root


parser = argparse.ArgumentParser(description='App to post the filters generated by Magic Beans to Yamaha PEQ.')

parser.add_argument('--ip', type=str, help='IP of the Yamaha AVR')
parser.add_argument('--input', type=str, help='MB filters txt file')
parser.add_argument('--dry-run', action='store_true', help='Do not post changes to the AVR')
parser.add_argument('--verbose', action='store_true', help='Increase output verbosity')

# Parse the arguments
args = parser.parse_args()

with open(args.input, 'r') as file:
    lines = file.read()

myxml = create_peq_request_xml(lines)

# # Parse the XML string
xml_str = ET.tostring(myxml, encoding='utf-8', method='xml')

# Pretty print the XML
xml_str_pretty = minidom.parseString(xml_str).toprettyxml(indent="  ")

if args.verbose:
    print(xml_str_pretty)

# Replace with your AVR's IP address
# avr_ip = "192.168.88.253:80"

if not args.dry_run:
    url = f"http://{args.ip}/YamahaRemoteControl/ctrl"
    payload = xml_str_pretty

    headers = {'Content-Type': 'application/xml'}
    response = requests.post(url, headers=headers, data=payload)

    if response.status_code == 200:
        response_xml = ET.fromstring(response.text)
        rc_value = response_xml.get("RC")

        if rc_value == "0":
            print("PEQ values updated successfully!", response.status_code)
        else:
            print("Failed to update PEQ values:", response.text)
    else:
        print("Failed to update PEQ values:", response.status_code)
        print(response.text)
